### ISSUE TITLE
Cannot open existing database or import from KeePass 1 and CSV

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.keepassxc.KeePassXC#1]
Version:
```
$ flatpak info org.keepassxc.KeePassXC
Ref: app/org.keepassxc.KeePassXC/x86_64/stable
ID: org.keepassxc.KeePassXC
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2017-12-18 23:06:48 +0000
Subject: Turn on unit tests for keepassxc (4c02d2ed)
Commit: 53be5cce93a27c08f3628575312822155a8697d602e8ce370e5369fa90b3ac4a
Parent: -
Location: /var/lib/flatpak/app/org.keepassxc.KeePassXC/x86_64/stable/53be5cce93a27c08f3628575312822155a8697d602e8ce370e5369fa90b3ac4a
Installed size: 6.1 MB
Runtime: org.kde.Platform/x86_64/5.9
```
Steps to reproduce:
* Click "Open existing database"
* Nothing happens
* Click "Import from KeePass 1"
* Nothing happens
* Click "Import from CSV"
* Nothing happens

Thank you very much!

**Comment by AsavarTzeth** [comment]
Thank you for informing us.

I am able to reproduce this. Unfortunately I don't think it is anything I can fix in the manifest.

What I do know is that this used to work some time ago. I don't know when and why it stopped working, but I suspect a change in the KDE Runtime / QT Flatpak Plugin has caused this.

**Comment by jurf** [comment]
Can reproduce this too, makes this effectively useless for me :-/

**Comment by AsavarTzeth** [comment]
I just tried `org.kde.Platform/x86_64/5.9 flathub 8030e3fac64c`; ostree log:

```
commit 8030e3fac64c32590a24e5b60700f0b61f13d0ae1a29a15b9219d37cee631bdb
Date:  2018-01-09 03:46:06 +0000

    Fix support for flatpak FileChooser portal (bd2210a9)

    Name: org.kde.Platform
    Arch: x86_64
    Branch: 5.9
    Built with: Flatpak 0.10.2
```

Everything now appears to be working again.

Links to relevant commits:

- https://phabricator.kde.org/R257:bd2210a9cd540003f9b6eb6704e105fa18430e8a
- https://github.com/KDE/flatpak-kde-runtime/commit/bd2210a9cd540003f9b6eb6704e105fa18430e8a

**Comment by Bittyby** [comment]
I ran into the exact same problem and still have not found a solution.
I have exactly the same problem with dolphin, maybe VS Code is sick for the same reason.

**Comment by AsavarTzeth** [comment]
@Bittyby I don't see how this is possible any more. When this issue was raised I did not allow direct access to the host file system, which likely was the cause.

Now I set `--filesystem=host` which changes everything, which means KeePassXC can access all files directly. The idea is to remove this in time, but only when all issues have been resolved.
