### ISSUE TITLE
Safe and secure default permissions

### ISSUE THREAD

**Issue by daniel-j-h** [flathub/org.keepassxc.KeePassXC#101]
Hey folks, awesome work here packaging KeePassXC as a flatpak :raised_hands:

I've been looking at the permissions seeing we are handing out a good amount of permissions by default e.g.
1. Network access only to download favicons
2. Access to the full host filesystem (instead of e.g. just the home dir)
3. Access to all devices like webcams and all that, in case of Yubikey support

- https://github.com/flathub/org.keepassxc.KeePassXC/blob/bea81b37c83c1a142e84db01466ce4778dc3bcb3/org.keepassxc.KeePassXC.yml#L24-L25

- https://github.com/flathub/org.keepassxc.KeePassXC/blob/bea81b37c83c1a142e84db01466ce4778dc3bcb3/org.keepassxc.KeePassXC.yml#L30-L32

- https://github.com/flathub/org.keepassxc.KeePassXC/blob/bea81b37c83c1a142e84db01466ce4778dc3bcb3/org.keepassxc.KeePassXC.yml#L26-L27

Because KeePassXC is a password manager and my tinfoil hat is comfy, I'm proposing the following:
1. By default, let's remove network permissions, the upside of having fancy favicons does not outweigh the downside of a password manager having network access just for this one convenience feature
2. By default, let's remove access to the full file system, and instead only allow access to the user's home dir; that sounds like a good compromise unless I'm missing why KeePassXC would need access to the full file system
3. By default, let's remove access to all devices; folks with Yubikeys are tech-savy enough to enable it

And then have a few words in the docs how users can enable these features e.g. with flatseal or the equivalent commands

![flatseal-keepassxc](https://user-images.githubusercontent.com/527241/198051679-34f08c7e-0196-4f8d-8e79-5625034a7223.jpg)

This way the KeePassXC flatpak will be more safe and secure by default, and users can still have their functionality by toggling a switch if they want to. Because at the moment 99% of users will run KeePassXC with the default permissions even though they probably don't even have a Yubikey, and don't care about favicons downloaded via the network.

What do you think? (cc @crepererum h/t for the flatseal shout)

**Comment by o-kotb** [comment]
I believe `--filesystem=host` is used for ssh-agent integration.

**Comment by droidmonkey** [comment]
I won't be removing any permissions. Those that want more protection can use flatseal to REMOVE them. We handle an ungodly amount of dumb issues and complaints with snaps. Your recommendations will cause us to have those same things happen with flatpak.

**Comment by droidmonkey** [comment]
Can you tell me what the threat vector is for an app to have access to the file system? You aren't running it as root, are you?

**Comment by droidmonkey** [comment]
PCSC is a specific interface. Yubikeys are not PCSC when plugged into USB. They are when using NFC readers though.

**Comment by o-kotb** [comment]
> I would argue that people might use the flatpak thinking it is more secure/sandboxed than 
> alternatives when really out of the box it isn't.

Maybe in the early days of Flatpak. But it has become more mainstream 
since then, and nowadays it's seen as the simple and easy installation 
method that just works on any distro.

-- 
Omar Kotb

**Comment by Hasshu** [comment]
> `--socket=fallback-x11` might be able to replace `--socket=x11`, although `--socket=ipc` will still need to exist, however keepassxc wayland support [still isnt complete](https://github.com/keepassxreboot/keepassxc/labels/platform%3A%20Linux%20-%20Wayland)

Incidentally, are there any blockers for replacing `--socket=x11` with `--socket=fallback-x11`? If I'm not mistaken, the latter [should](https://docs.flatpak.org/en/latest/sandbox-permissions.html#standard-permissions) make KeePassXC try to use Wayland by default (and no longer be called unsafe by Flathub and GNOME Software for using "a legacy windowing system").

**Comment by droidmonkey** [comment]
We don't necessarily want to use Wayland by default as it breaks Auto-Type and clipboard clearing.

**Comment by Hasshu** [comment]
Does it mean that KeePassXC running under a Wayland session via XWayland retains the said functionality somehow? (Am not particularly knowledgeable in this area.)

**Comment by droidmonkey** [comment]
It does because it is actually running on an X11 server (as a client), XWayland is an interface between the X11 server and Wayland compositor. Any other app running on that x11 server will be capable of receiving auto type.

**Comment by droidmonkey** [comment]
That elevation of privilege sounds like a security problem that flatpak needs to solve. Has that been reported to them?

**Comment by Tedpac** [comment]
As much as I dislike the idea of such critical software as a password manager having more permissions by default than it should, restricting these permissions, causing certain KeePassXC functionality to fail, could have the counterproductive effect of causing some users to decide not to install KeePassXC with Flatpak, or even, they may decide to use a different password manager thinking KeePassXC is broken. Additionally, it will most likely generate a wave of criticism similar to [this one](https://www.reddit.com/r/linux/comments/1couviy/keepassxc_debian_maintainer_has_removed_all/).

**Comment by daniel-j-h** [comment]
Thanks for the discussion folks! I'm closing this as we have heard all sides and the maintainers will rightfully not change defaults.

**Comment by ng0177** [comment]
Yubikeys on USB as a challenge response seem still not be supported by the latest `FlatSeal` "No hardware keys detected". Which permissions are required in `FlatSeal` to provide a kind of root access? (The latter should not be required anyways).

**Comment by crepererum** [comment]
For USB keys, you need to enable full device accesa at the moment. That's obviously not great for security since this includes all kinds of devices. Proper USB portal handling is currently being worked on by the Flatpak ecosystem, see https://www.phoronix.com/news/GNOME-USB-Flatpaks-Portal (same applies to other DEs).
