### ISSUE TITLE
KeePassXC no longer respects GTK dark theme

### ISSUE THREAD

**Issue by arielnmz** [flathub/org.keepassxc.KeePassXC#105]
I'm reopening this issue since the other one (https://github.com/flathub/org.keepassxc.KeePassXC/issues/42) was closed and there was no response to my last comment, and it is still present in KeepassXC version:

```
KeePassXC - Community-driven port of the Windows application “KeePass Password
Safe”

          ID: org.keepassxc.KeePassXC
         Ref: app/org.keepassxc.KeePassXC/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.7.4
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 38.7 MB
     Runtime: org.kde.Platform/x86_64/5.15-22.08
         Sdk: org.kde.Sdk/x86_64/5.15-22.08

      Commit: ce59520f98630092cfd09a1f88fbad3b4970fbac97c7ca13eb315a3b74321b8b
      Parent: bcb0cbd96bb1af0186dc0bea6b221c15774ee858971932d04f54916734e87c06
     Subject: Bump release to 2.7.4 (75a0f1dc)
        Date: 2022-10-30 02:17:56 +0000
```

.profile:

```

# Theme properties
export GTK_THEME="Arc-Dark"
export GTK_THEME_VARIANT="dark"

# Some tips from here:
# https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#Flatpak_Qt_apps_do_not_use_Gnome_Adwaita_dark_theme
export QT_QPA_PLATFORMTHEME="gnome"

# Some other good tips here:
# https://gist.github.com/jmrf/4de7a72c0c7a07afcb0b5f880dc9a2dc
# Configure through dconf
# Not needed unless a settings manager is used e.g. xfsettings or gnome-settings
# NOTE: Some flatpak applications can only get settings from settings daemons
dconf write /org/gnome/desktop/interface/gtk-theme "'${GTK_THEME}'"
dconf write /org/gnome/desktop/interface/gtk-color-scheme "'${GTK_THEME_VARIANT}'"
dconf write /org/gnome/desktop/interface/icon-theme "'WhiteSur-dark'"
dconf write /org/gnome/desktop/interface/font-name "'sans 10'"
dconf write /org/gnome/desktop/interface/monospace-font-name "'monospace 10'"
```

![image](https://user-images.githubusercontent.com/24735547/216849778-bcb641b7-20fb-4024-a978-6b70aa77577f.png)

**Comment by pm4rcin** [comment]
Hi, try using the last option from the list. The classic allowed me to use Adwaita-Dark just fine so I guess it should work for you too. I guess something is broken on keepassxc side because it doesn't work in non-flatpak too. As an example it works just fine on RPCS3 flatpak which has the same runtime as KPXC. Even though it was implemented https://github.com/keepassxreboot/keepassxc/pull/7422 it doesn't work. I use it in [dwl](https://github.com/djpohly/dwl) (wlroots based) but I don't know if it makes any difference.

**Comment by superuser-miguel** [comment]
I tried this recently and after a reboot it has worked `flatpak override --filesystem=~/.themes; `

**Comment by arielnmz** [comment]
Just upgraded to Fedora 40 and this issue is back again. Setting the theme manually to dark works fine but Automatic defaults to light.

Setting theme via gsettings does not work:

```
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
```

Copying the gtk-3.0 settings into `~/.var/app/org.keepassxc.KeePassXC/config/gtk-3.0` does not work either:

$ cat $XDG_CONFIG_HOME/gtk-3.0/settings.ini
```
[Settings]
gtk-application-prefer-dark-theme = true
gtk-theme-name = Adwaita-dark
gtk-font-name = sans 10
```

**Comment by droidmonkey** [comment]
Recommend filing a bug with flatpak
