### ISSUE TITLE
KPXC doesn't honor ConfirmAccessItem in [FdoSecrets] when it cannot find the executable path

### ISSUE THREAD

**Issue by StayPirate** [flathub/org.keepassxc.KeePassXC#109]
The problem of fingerprinting short-live processes was lengthy discussed https://github.com/keepassxreboot/keepassxc/issues/7571 and https://github.com/keepassxreboot/keepassxc/issues/6458. The quickest workaround is to set `ConfirmAccessItem=false` under `[FdoSecrets]` to revert to 2.6.x behavior.

Flatpaked KPXC does not honor the `ConfirmAccessItem` option and keep showing the following dialog every time Nextcloud-client starts, even though I have `ConfirmAccessItem=false`

![image](https://user-images.githubusercontent.com/37073343/224490294-c96ce29c-6108-4880-9ced-0e5e1ee2775d.png)

Please note that nextcloud-client is installed via Flatpak as well. I have no memories of this weird behavior in my previous setup where both KPXC and Nextcluoud-client where installed via the distro's packet manager.

**Comment by StayPirate** [comment]
My best guess is that KPXC has no visibility over the nextcloud binary because it's from another flatpak container. Hence, it behaves like shown above.

IMO if `ConfirmAccessItem` is set to `false` KPXC should not show that dialog and allows the process to access the requested data right away.

**Comment by droidmonkey** [comment]
This is a bug in KeePassXC itself
