### ISSUE TITLE
Opening an existing database results in read-only mode

### ISSUE THREAD

**Issue by AsavarTzeth** [flathub/org.keepassxc.KeePassXC#11]
Distribution: Arch Linux
Flatpak: 0.11.3
xdg-desktop-portal: 0.10

KDE Platform:
```
Ref: runtime/org.kde.Platform/x86_64/5.9
ID: org.kde.Platform
Arch: x86_64
Branch: 5.9
Origin: flathub
Collection ID: 
Date: 2018-02-26 20:55:31 +0000
Subject: Include the patch that makes all applications crash on wayland (61f1b7ee)
Commit: 558bfa8ec814ff2bd34656cbc66807eaa98ea0050c993699e4be18ce1e7b3fd8
Parent: ea891f4a918fe3f17df3a94dd78f9c8172c9bce9a14311dd6400dcb37cd0b8b9
Location: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.9/558bfa8ec814ff2bd34656cbc66807eaa98ea0050c993699e4be18ce1e7b3fd8
Installed size: 1,1 GB
```

Steps to reproduce:

1. Create a new database, name it "test" with a password "test".
2. Close KeePassXC
3. Open KeePassXC and enter your password
4. Execute: `ls /run/user/$UID/doc/by-app/org.keepassxc.KeePassXC/* | grep test`.
    Output should be similar to:
```
-rw-r--r-- 0 user user 1118  1 mar 12.05 test.kdbx
```

At this point everything works. The problem occurs when you press "Cancel", closes the database tab (if you have multiple databases open), or otherwise exits the database, without closing the application.

5. Open an existing database or choose from the list of recently used databases.
6. The moment you try to open the file:
```
-r--r--r-- 0 user user 1118  1 mar 12.05 test.kdbx
```

KeePassXC is now permanently in read-only mode for that database. Is there a specific way the application needs to open a file in order for the document portal to grant it read-write access?

**Comment by ysteina** [comment]
I experience this too with version 2.3. I never really got the chance to test the previous version with Flatpak, so I can't tell if this is a regression. 
FWIW, the official snap version now also cannot save a database after having opened an existing one.

**Comment by aiamuzz** [comment]
i experience similar issue ... existing database isn't opening ... the applicaton freezes when i try to open one. Killing the application in system monitor is the only way to close it.

**Comment by joergister** [comment]
same problem here.
Having read only access to the database when opening with the keepassxc flatpak, results in not being able to edit the database and save the changes, because read only access means that the database can not be overwritten. This sucks, because every time I change something in the database, I always have to save the changed database in another folder or so, and later I have to replace my old database with my new database.
This problem does not appear, when I'm using the appimage from the keepassxc website.

**Comment by joergister** [comment]
I did a 

` flatpak run --log-session-bus --log-system-bus org.keepassxc.KeePassXC`  

and the changed and tried to overwrite a database. 
don't know if it helps

Output:

```
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.ScreenSaver
C3: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.ScreenSaver
C4: -> org.freedesktop.DBus fake AddMatch for com.canonical.AppMenu.Registrar
C5: -> org.freedesktop.DBus fake GetNameOwner for com.canonical.AppMenu.Registrar
C6: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.Notifications
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.Notifications
C8: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.login1.Manager
C9: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.login1.Manager
C10: -> org.freedesktop.DBus fake AddMatch for org.gnome.ScreenSaver
C11: -> org.freedesktop.DBus fake GetNameOwner for org.gnome.ScreenSaver
C12: -> org.freedesktop.DBus fake AddMatch for org.kde.StatusNotifierWatcher
C13: -> org.freedesktop.DBus fake GetNameOwner for org.kde.StatusNotifierWatcher
C14: -> org.freedesktop.DBus fake AddMatch for org.keepassxc.KeePassXC
C15: -> org.freedesktop.DBus fake GetNameOwner for org.keepassxc.KeePassXC
C16: -> org.freedesktop.DBus fake AddMatch for org.gnome.SessionManager.Presence
C17: -> org.freedesktop.DBus fake GetNameOwner for org.gnome.SessionManager.Presence
C18: -> org.freedesktop.DBus fake AddMatch for org.gnome.SessionManager
C19: -> org.freedesktop.DBus fake GetNameOwner for org.gnome.SessionManager
C20: -> org.freedesktop.DBus fake AddMatch for com.canonical.Unity.Session
C21: -> org.freedesktop.DBus fake GetNameOwner for com.canonical.Unity.Session
C22: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.login1.Session
C23: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.login1.Session
C24: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.portal.*
C25: -> org.freedesktop.DBus fake AddMatch for org.keepassxc.KeePassXC.*
C26: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C5
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C9
*SKIPPED*
B11: <- org.freedesktop.DBus return from C10
*SKIPPED*
B12: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C11
*SKIPPED*
B13: <- org.freedesktop.DBus return from C12
*SKIPPED*
B14: <- org.freedesktop.DBus return from C13
*SKIPPED*
B15: <- org.freedesktop.DBus return from C14
*SKIPPED*
B16: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C15
*SKIPPED*
B17: <- org.freedesktop.DBus return from C16
*SKIPPED*
B18: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C17
*SKIPPED*
B19: <- org.freedesktop.DBus return from C18
*SKIPPED*
B20: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C19
*SKIPPED*
B21: <- org.freedesktop.DBus return from C20
*SKIPPED*
B22: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C21
*SKIPPED*
B23: <- org.freedesktop.DBus return from C22
*SKIPPED*
B24: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C23
*SKIPPED*
B25: <- org.freedesktop.DBus return from C24
*SKIPPED*
B26: <- org.freedesktop.DBus return from C25
*SKIPPED*
B27: <- org.freedesktop.DBus return from C26
C27: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C28: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
*SKIPPED*
C29: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C30: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
B28: <- org.freedesktop.DBus return from C27
*SKIPPED*
B29: <- org.freedesktop.DBus return from C28
*SKIPPED*
C31: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C32: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C33: -> org.freedesktop.DBus call org.freedesktop.DBus.NameHasOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.a11y.Bus, policy: 0 (required 1)
B30: <- (no sender) return from C33
*REWRITTEN*
C34: -> org.freedesktop.DBus call org.freedesktop.DBus.NameHasOwner at /org/freedesktop/DBus
B31: <- org.freedesktop.DBus return from C34
C35: -> org.freedesktop.DBus call org.freedesktop.DBus.RequestName at /org/freedesktop/DBus
B32: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameOwnerChanged at /org/freedesktop/DBus
B33: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B34: <- org.freedesktop.DBus return from C35
C36: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C37: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C38: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B35: <- org.freedesktop.DBus return from C38
C39: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C40: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C41: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B36: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C41
C42: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C43: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C44: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B37: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C44
C45: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C46: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C47: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
Filtering message due to arg0 com.canonical.Unity, policy: 0 (required 1)
B38: <- (no sender) return from C47
*REWRITTEN*
C48: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C49: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C50: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
QObject::startTimer: Timers cannot have negative intervals
C51: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.FileChooser.SaveFile at /org/freedesktop/portal/desktop
B166: <- :1.49 return from C51
C52: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
B168: <- :1.49 signal org.freedesktop.portal.Request.Response at /org/freedesktop/portal/desktop/request/1_113/qt889885083
C53: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
```

**Comment by einsteinsfool** [comment]
I also have this problem with KDE.
**ahayzen** on IRC provided me with the following solution:
`flatpak override --user --filesystem=~/Documents org.keepassxc.KeePassXC`
**AdrianCeleste** said that home or XDG_DOCUMENT are no longer exposed as read-write.
**alexanderW** added that there was an issue with the portal and the KDE SDK that caused the wrong path being shown in TeXstudio and that maybe KeePassXC just needs rebuilding.

**Comment by AsavarTzeth** [comment]
I actually have not experienced this issue for several months. It occurred to me now that I forgot to update this issue to reflect that. With that in mind I have to first assume this is issue is specific to you who still experience this.

- Do you still experience this issue with a fully up-to-date `flatpak`? (Current: Flatpak 0.11.8.3)
- What versions of `xdg-desktop-portal` and `xdg-desktop-portal-kde` (in the case of Plasma users) is installed?
- What version/commit of the KDE runtime is installed? `flatpak info org.kde.Platform//5.10`
- What version/commit of the app is installed? `flatpak info org.keepassxc.KeePassXC`

**Comment by einsteinsfool** [comment]
You're right. Building the newest version 0.11.8.3 fixed the problem.

**Comment by AsavarTzeth** [comment]
Nice to hear! I am closing this since it appears to no longer be an issue.

If anyone still experiences this, please say so, but please answer the the questions in my last comment. Also test with fully up-to-date software.

**Comment by ysteina** [comment]
I still experience this issue (and it's the reason I use the Appimage instead) on KDE Neon with Plasma 5.13.4 (OS is based on Ubuntu 18.04)

- Flatpak version 1.0.0 from alexlarsson's ppa
- xdg-desktop-portal 1.0 and xdg-desktop-portal-kde 5.13.4
- flatpak info org.kde.Platform//5.9: 
Commit: 42d2df3bf0ea94ed74df01d7b5b9fb0e9a25d1fbd1a4f1355ce96c7ddbd6d618
Parent: 94cb4d06a739a25dd7d43c6ae288c8f5db4cb87884ec1d580433aec2724a7377
- flatpak info org.keepassxc.KeePassXC:
Commit: 15aa7b7b4e1b2225dd9e5778a5088ce79e2bdcb2f05d54fbb216248d619da4c3
Parent: 8067d1b74b1c6768843c020820f8a386ba89d4298b9a999f9cd837a9108ee146
Runtime: org.kde.Platform/x86_64/5.9

**Comment by joergister** [comment]
Have you tried it on another distro in a VM?
Like Fedora?

**Comment by AsavarTzeth** [comment]
Well everything is certainly up-to-date.

Have you checked if the file is actually read-only? See my steps in the top comment. I tried to reproduce it again and failed; to me it is no longer read-only.

**Comment by ysteina** [comment]
So it looks like the Flatpak version cannot write to KDBX files that have been *created* by the official Appimage version. If I *create* a database with the Flatpak version, then modify it with the Appimage version, then open it with the Flatpak version again, it works.

**Comment by AsavarTzeth** [comment]
Strange, my database was created by a regular distro package. But that was a long time ago.

In any case I would not phrase it like that. It has nothing to do with the database being created by the AppImage version, but rather if it is opened from within the flatpak sandbox or outside (it is always from the outside if you open a pre-existing database). There have been, and still are, some issues in this area.

**Comment by joergister** [comment]
Well for me (Fedora 28 KDE it is working just fine with databases that already existed.
