### ISSUE TITLE
Please remove access to /tmp or document why it is necessary

### ISSUE THREAD

**Issue by bauen1** [flathub/org.keepassxc.KeePassXC#114]
The current flatpak requires access to the hosts `/tmp`:
https://github.com/flathub/org.keepassxc.KeePassXC/blob/24099ca07c2ad52c6da33a48e9be9569a3f3ae46/org.keepassxc.KeePassXC.yml#L34-L35

The yaml mentions a patch that can be / should be upstreamed ?
But I can't seem to find this patch, so is mounting `/tmp` still necessary ?

On the other hand <https://github.com/flathub/org.keepassxc.KeePassXC/pull/89/files#r845384585> seems to imply, that this access is still necessary and can't be removed ?
In which case I'd be interested to know, why sharing files with other applications doesn't also work through the xdg-document-portal, like giving KeePass access to a file.

Digging for this has also made me realize, that I would really like for flatpak to expose a comment/explanation for permissions granted to an app.

Thanks for your time in packaging this app for flathub :slightly_smiling_face:

**Comment by droidmonkey** [comment]
We need it to perform alternative saving methods. You can change permissions as you please using FlatSeal.
