### ISSUE TITLE
Fix permissions to use SSH Agent with Flatpak 

### ISSUE THREAD

**Issue by droidmonkey** [flathub/org.keepassxc.KeePassXC#117]
For those landing here and using the official flatpak, the current (2023.09+) flatpak enables the ssh-auth socket by default, however it is missing the environment variable setting. To fix this, using "Flatseal", add an environment variable to the keepassxc flatpak configuration, 
```
SSH_AUTH_SOCK=$SSH_AUTH_SOCK 
```
and relaunch keepassxc.

_Originally posted by @arigit in https://github.com/keepassxreboot/keepassxc/issues/8460#issuecomment-1722587051_

**Comment by jgonyea** [comment]
This doesn't seem to be working for me.  I still get the "No agent running, cannot list identities."

```
echo $SSH_AUTH_SOCK                                                                                                        
/run/user/1000/ssh-agent.socket
```

and
```
$ ps aux | grep ssh                                                                                                         
deck        6010  0.0  0.0   5840  3896 ?        Ss   19:26   0:00 /usr/bin/ssh-agent -D -a /run/user/1000/ssh-agent.socket

```

**Comment by cgredig** [comment]
> This doesn't seem to be working for me. I still get the "No agent running, cannot list identities."
> 
> ```
> echo $SSH_AUTH_SOCK                                                                                                        
> /run/user/1000/ssh-agent.socket
> ```
> 
> and
> 
> ```
> $ ps aux | grep ssh                                                                                                         
> deck        6010  0.0  0.0   5840  3896 ?        Ss   19:26   0:00 /usr/bin/ssh-agent -D -a /run/user/1000/ssh-agent.socket
> ```
> 
> Followup edit: I had a misconfiguration in my `~/.config/environment.d/ssh_auth_socket.conf` file. This is working for me now.

Could you post how your ssh_auth_socket.conf looked before and after? I have the same issue, the env variable contains the correct path and it is recognized by KeepassXC but it still complains that the agent is not running which is not true.
