### ISSUE TITLE
Tray icon type not match expected appearance

### ISSUE THREAD

**Issue by notfirefox** [flathub/org.keepassxc.KeePassXC#120]
### Summary
It appears that all tray icon types work, except for the _Monochrome (dark)_ option.
The other ones, i.e. _Monochrome (light)_ and _Colorful_ seem to be working just fine.

Please see the images below for a comparison of the actual and the expected appearance.
I have also provided a brief explanation on how to reproduce this issue.

### Steps to reproduce

First, follow along with KeePassXC being installed from the package manager of your distribution. 

1. Open KeePassXC, but do not unlock the database
2. Go to the settings menu
3. Locate `Tray icon type` and change its setting
4. Observe the icon in the tray menu

Uninstall KeePassXC and install it from Flatpak (FlatHub). Repeat steps 1-4.

### Actual 

**System information**
```
Fedora Linux 39 KDE
KeePassXC RPM keepassxc-2.7.6-6.fc39
```

**Monochrome (light)**
![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/138280734/a6f0513b-80f8-4369-87a6-3f0db5ea73da)

**Monochrome (dark) <=== (this is what it actually looks like)**
![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/138280734/e931f786-9338-47ae-aed9-5c27fbbb2345)

**Colorful**
![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/138280734/600505b2-589a-411a-abc2-8767528a2f98)

### Expected

**System information**
```
Fedora Linux 39 KDE
KeePassXC Flatpak 2.7.6 stable
```

**Monochrome (light)**
![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/138280734/99ae5df7-86ae-4284-8e89-a9d172613615)

**Monochrome (dark) <=== (this is what it should look like)**
![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/138280734/55e8518e-31d8-49db-89e2-1fe29ea1cbee)

**Colorful**
![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/138280734/90d9b0fa-5115-445e-bb9e-25c5eda338d8)

**Comment by notfirefox** [comment]
@droidmonkey I'm so sorry, I accidentally switched it up the system information portion. The RPM one is the one that works as expected (please see the images above again, I fixed it). And the Flatpak version uses a colorful icon, whereas it should be _Monochrome (dark)_.

**Comment by droidmonkey** [comment]
Oh well that is interesting. I'll test this myself

**Comment by droidmonkey** [comment]
Worked fine for me, Fedora 39:

![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/2809491/21e42380-8927-4858-b199-61caa0d9db02)

![image](https://github.com/flathub/org.keepassxc.KeePassXC/assets/2809491/e3fd8055-0c5c-482a-bb48-ca43eb1e32d1)
