### ISSUE TITLE
Cannot open non-default browser with flatpak.

### ISSUE THREAD

**Issue by debmint** [flathub/org.keepassxc.KeePassXC#124]
Running Mint 21.3 on one computer and Debian Bookworm on another.  I removed and purged my deb installs of keepassxc and installed flatpak of version 2.7.7 in order to utilize secure keys.  My default browser is Librewolf, but I have a few websites I need to use alternate browsers some with firefox and others with brave.  When I attempt to call up these sites (using keepassxc-browser) ,  nothing happens.  When I call it from the terminal on Mint, it did display an error about not being able to access a library function for firefox, but otherwise there is no output.  There is one warning produced both from the command line and in .xsession-errors:

Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed

The sites that use the default browser (with no "cmd//..." prefix work as expected.  On Mint, I removed the flatpak and installed from the ppa as recommended on the keepassxc website and the sites using the alternate browsers work as expected.

I am not familiar with flatpaks but it would seem like it could be a permissions issue.  I played with some of the permissions but with no improved results.  I also tried calling keepassxc from the command line using the option --filesystem=host-os but with no luck.  This may not be a flatpak issue, but since a native install of 2.7.7 corrects the issue, it seems to indicate to me that it certainly might be.

**Comment by droidmonkey** [comment]
Please post the full cmd:// line (minus the web address) so I can try to replicate.

**Comment by debmint** [comment]
Closing issue as being something not fixable
