### ISSUE TITLE
html form filling on different devices

### ISSUE THREAD

**Issue by shieling** [flathub/org.keepassxc.KeePassXC#129]
I have a most peculiar problem on one of my websites. The website has a login form with fields of username and password. The server deals with all the necessary checking and security when someone logs in, which normally works fine. However, I have discovered that the verification fails when a username ‘admin’ logs in, but only on some devices. I have found out that on the device where the login fails a space is added to either the username or the password, which of course makes the verification fail. The device where the login fails differs from day to day. On one day I can login on my iPad but not on my Linux laptop. On another day the iPad works okay but the laptop fails.
This problem ONLY occurs when the username is ‘admin’ - all other normal users never have a problem. When the problem occurs ALL browsers on the device fail.
I have ‘fixed’ the problem by using the PHP trim() function to strip the random spaces, but I do not understand why the space appears in the first place.
So my question is “Has anyone else seen this issue and also does anyone understand why it happens?”

**Comment by droidmonkey** [comment]
Not sure what this has to do with KeePassXC. You also posted this in our website repo.

**Comment by shieling** [comment]
Hi Jonathan,Thanks for pointing this out- my mistake. I will try to  find the correct forum. RegardsAndyOn 15 Jun 2024, at 23:59, Jonathan White ***@***.***> wrote:﻿
Closed #129 as not planned.
