### ISSUE TITLE
Development branch build doesn't have QuickUnlock

### ISSUE THREAD

**Issue by CD11b** [flathub/org.keepassxc.KeePassXC#134]
I [modified](https://github.com/CD11b/org.keepassxc.KeePassXC/blob/a2029899b4fd70319b33feb43be191cdea95b38d/org.keepassxc.KeePassXC.yml) the manifest file to build from develop, and it built successfully. I was surprised to see "Enable database quick unlock (Touch ID / Windows Hello)" greyed out despite being on the latest 2.8.0. My snapshot build AppImage works as expected, which should be built from the same commit. There are some differences in the Debug info, though. 

I'd really like to have QuickUnlock available in a Flatpak sanbox, so I'd appreciate if someone would point me to the right direction.

OS: Arch Linux x86_64
Kernel: Linux 6.9.10-arch1-1
Flatpak 1.15.8
flatpak-builder-1.4.4

![image](https://github.com/user-attachments/assets/340b28a9-2730-463d-bcd6-d4dea390e29e)

KeePassXC-2.8.0-snapshot-x86_64.AppImage
> KeePassXC - Version 2.8.0-snapshot
> Build Type: Snapshot
> Revision: afe634d
> Distribution: AppImage
> 
> Qt 5.12.8
> Debugging mode is disabled.
> 
> Operating system: Arch Linux
> CPU architecture: x86_64
> Kernel: linux 6.9.10-arch1-1
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - Passkeys
> - SSH Agent
> - KeeShare
> - YubiKey
> - Secret Service Integration
> 
> Cryptographic libraries:
> - Botan 2.12.1

Flatpak Build
> KeePassXC - Version 2.8.0
> Revision: afe634d
> Distribution: Flatpak
> 
> Qt 5.15.10
> Debugging mode is disabled.
> 
> Operating system: KDE Flatpak runtime
> CPU architecture: x86_64
> Kernel: linux 6.9.10-arch1-1
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - Passkeys
> - SSH Agent
> - KeeShare
> - YubiKey
> - Secret Service Integration
> 
> Cryptographic libraries:
> - Botan 3.3.0

**Comment by droidmonkey** [comment]
This may not be possible given how quick unlock works on Linux using polkit.

**Comment by CD11b** [comment]
Unfortunate to hear. For anyone wondering, I "worked around" this by changing the binary's path in the native messaging file to the AppImage. KeePassXC won't be sand-boxed, of course, but browser integration still works fine.
