### ISSUE TITLE
Yubikeys on USB as a challenge response in FlatSeal

### ISSUE THREAD

**Issue by ng0177** [flathub/org.keepassxc.KeePassXC#135]
As described in https://github.com/flathub/org.keepassxc.KeePassXC/issues/101 Yubikeys on USB as a challenge response seem still not be supported by the latest FlatSeal "No hardware keys detected". Which permissions are required in FlatSeal to provide a kind of root access? (The latter should not be required anyways).

**Comment by droidmonkey** [comment]
You might have to install the appropriate udev rules to allow access to the yubikey itself. This would be outside of flatpak permissions.

**Comment by ng0177** [comment]
I see. Any directions on where to find the appropriate commands?

**Comment by droidmonkey** [comment]
what is your linux distro?

**Comment by droidmonkey** [comment]
Works great on Fedora 40, Gnome, nothing special

![image](https://github.com/user-attachments/assets/c55fc74c-5d9b-4459-af59-84383bdd6d48)

**Comment by ng0177** [comment]
> what is your linux distro?

https://fedoraproject.org/atomic-desktops/silverblue/

**Comment by droidmonkey** [comment]
Recommend filing a bug with the silverblue team, this isn't anything we can fix at our level.

**Comment by ng0177** [comment]
It has turned out that the issue is not access rights. It actually works but the error message is misleading. A challenge-response slot was not configured on the Yubikey. So, it is recognized but the slot is not accessible should be the correct message.

**Comment by droidmonkey** [comment]
That's a good point. We should be indicating when we find keys but no slots.
