### ISSUE TITLE
Update org.freedesktop.Platform and org.kde.Platform.

### ISSUE THREAD

**Issue by ndiruhniu** [flathub/org.keepassxc.KeePassXC#136]
KeePassXC is still using org.freedesktop.Platform and org.kde.Platform branch 23.08. Could you update it to 24.08?

**Comment by droidmonkey** [comment]
It is not available for use yet, apparently: https://github.com/flathub/org.keepassxc.KeePassXC/pull/137#issuecomment-2466179658

Also searched flathub repos:

![image](https://github.com/user-attachments/assets/72894899-700a-453a-b14f-d569d6474113)

**Comment by ndiruhniu** [comment]
Okay, but what about org.freedesktop.Platform?

**Comment by droidmonkey** [comment]
org.kde.Platform is built on top of org.freedesktop.Platform
