### ISSUE TITLE
error: Unknown socket type ssh-auth

### ISSUE THREAD

**Issue by CWhyMedia** [flathub/org.keepassxc.KeePassXC#23]
I get this error when I try to launch it:

`error: Unknown socket type ssh-auth, valid types are: x11, wayland, pulseaudio, session-bus, system-bus`

This only started happening after an update, I think something changed with flatpak platform related files?

**Comment by TingPing** [comment]
Your `flatpak` version is older than that feature.

**Comment by yaomtc** [comment]
Ah. It's the latest from the CentOS repos. Should I just try to find a newer Flatpak package for CentOS or compile it myself?

**Comment by AsavarTzeth** [comment]
See https://github.com/flathub/org.keepassxc.KeePassXC/commit/e2a7fbd54cce2a5ed7fac1de344892e0a024c8db for the relevant change.

I believe you need to build it yourself (if possible).

I wonder if it is possible to use an [override](http://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override). This new permission is only used for an optional feature, so if you don't need it you should ideally be able to disable it.

```
flatpak override --nosocket=ssh-auth org.keepassxc.KeePassXC
```

Or will this fail similarly?

**Comment by TingPing** [comment]
Flatpak 1.0 will be in RHEL soon. For now you can install from here: https://copr.fedorainfracloud.org/coprs/amigadave/flatpak-epel7/

**Comment by CWhyMedia** [comment]
> Ah. It's the latest from the CentOS repos. Should I just try to find a newer Flatpak package for CentOS or compile it myself?

Made this comment with the wrong account, so I figured I'd repost it here. Thanks for the information, @TingPing and @AsavarTzeth. I'll get flatpak updated.
