### ISSUE TITLE
Update 2.3.4

### ISSUE THREAD

**Issue by ifsanjry** [flathub/org.keepassxc.KeePassXC#24]
I think you guys are aware of the [new update](https://keepassxc.org/blog/2018-08-23-2.3.4-released/). Please update the software to 2.3.4.

Thanks

**Comment by AsavarTzeth** [comment]
Actually, this time I was unaware.

My feed aggregator intially picked up this release at 2018-08-23, but at that time 2.3.4 was just an RC.

It seems they just reused the same release tag, or something. Anyhow I never got a second notification.
