### ISSUE TITLE
KeePassXC no longer works on Linux Mint 18.3

### ISSUE THREAD

**Issue by Sl0vi** [flathub/org.keepassxc.KeePassXC#25]
I installed the flatpak through the software manager, but I can no longer launch the application.

If I try to launch it from the terminal I get the error:

error: Unknown socket type ssh-auth, valid types are: x11, wayland, pulseaudio, session-bus, system-bus

It used to work, I'm not sure what has changed.

**Comment by TingPing** [comment]
Grab a newer version of `flatpak` from the ppa: https://flatpak.org/setup/Ubuntu/

**Comment by Sl0vi** [comment]
I'd rather not add a ppa for something that is supposed to be a fully supported feature of my distro and flatpak.org says no additional setup should be required for Linux Mint 18.3 and newer.

**Comment by TingPing** [comment]
`flatpak` still works but this package uses a feature that was added after the version you are on. Sadly time travel has not been invented yet to our knowledge.

**Comment by TingPing** [comment]
Also the version of Flatpak you have is not actually supported, Mint has not kept up with bug fixes even.

**Comment by Sl0vi** [comment]
So should I submit a bug report with Linux Mint?

This is a bit worrisome since I thought flatpak was supposed to be a reliable way to install up to date applications.

**Comment by Sl0vi** [comment]
I've open a bug report with Linux Mint:

https://github.com/linuxmint/mintinstall/issues/212

**Comment by Sl0vi** [comment]
Flatpak has been updated in Linux Mint 18.3 and the KeepassXC flatpak launches correctly now.

This issue has been resolved.
