### ISSUE TITLE
Databases are opened in read-only mode

### ISSUE THREAD

**Issue by VosaXalo** [flathub/org.keepassxc.KeePassXC#26]
I'm using KDE Neon with Plasma 5.14 and KeePassXC flatpak 2.3.4.
Every database I select, it opens in read-only mode.
I can't update the database, and I don't know how to do it.

**Comment by TingPing** [comment]
In the file dialog it might have a checkbox to enable read-only or not. (The GTK version does)

**Comment by VosaXalo** [comment]
In KDE there is no read-only checkbox.
I can add that I use the same database with the Snap of KeePassXC without any issue. So, I believe that it's a problem of the flatpak package.

**Comment by TingPing** [comment]
Well that isn't related, this would be a limitation of `xdg-desktop-portal-kde` if anything.

**Comment by TingPing** [comment]
You can technically use `flatpak document-export` to manually get things in but that isn't very user friendly. You could also just put the database in `~/.var/app/org.keepassxc.KeePassXC/data`

**Comment by VosaXalo** [comment]
@TingPing Thank you for your suggestion, but I think I will wait until this issue is resolved.
In the meantime I can use the Snap.

**Comment by VosaXalo** [comment]
Hello @TingPing are there any news about this issue? Thanks.

**Comment by VosaXalo** [comment]
The skrooge guys have resolved this same issue (see the closed ticket above). 
I think they have added something like 
`--filesystem=host # needed for saving files`
to allow the saving of files.

**Comment by TingPing** [comment]
Yes that would obviously work but it is the wrong solution.

**Comment by Rex-On-GitHub** [comment]
Hi VosaXalo!
I don't have any code fixes for you, but I do have something that might be causing your problem.
On my installation of KeePassXC "automatically save after every change" seemed to have been checked by default. The save button would always be greyed out, making me believe my database was read-only. Un-checking it allowed the save option to become available.
I suggest seeing if that setting is enabled and is tricking you as it did me.

**Comment by VosaXalo** [comment]
Hi @Rex-On-GitHub ,
I thank you for your support, but unfortunately the issue has nothing to do with that.
When I open the database, it's already read-only, independently of the settings.
Moreover, the path of the file is displayed in a strange shape like this:
`/run/user/1000/doc/cbdd2a4c/keepassxc.kdbx`
and I think this has to do with the problem.

**Comment by Rex-On-GitHub** [comment]
Happy to make the effort! My paths show similarly.
`/run/user/1001/doc/cbb75b73/Keepass 2 Database.kdbx`

**Comment by AsavarTzeth** [comment]
Those "strange" paths are expected and a result of KeePassXC being sandboxed. It does not have direct access to those files. Instead, when you select a file to open, it is granted access to that file only via a portal API. It is then mounted at that "strange" path inside the sandbox.

See: #2 and flatpak/xdg-desktop-portal#141

**Comment by AsavarTzeth** [comment]
Is this still an issue? I recently pushed a new major application update that is worth testing.

**Comment by VosaXalo** [comment]
Unfortunately yes. The database I'm using is still opened in read-only mode.
I'm using KeepassXC updated to version 2.4.0 and flatpak engine version 1.3.0.

**Comment by VosaXalo** [comment]
With the update of today, now the database is opened correctly, and the app is finally usable.
Thank you.

**Comment by AsavarTzeth** [comment]
Glad to hear it.

This is actually a result of 8472f4626c8aa07831616821569eecccfe4c6545. There were just too many issues with related to the filechooser and/or document portal; i.e. I gave in and used `--filesystem=host` for now.

Now that Flathub has beta branches I opted to using that for sandboxed (portal based) file access. So anyone that wants it can use that.
