### ISSUE TITLE
Missing file extension (.kdbx) when saving new databases, or using Save as

### ISSUE THREAD

**Issue by fansari** [flathub/org.keepassxc.KeePassXC#27]
I have installed the flatpak version of KeePassXC on Fedora 29 Silverblue.

flatpak install flathub org.keepassxc.KeePassXC

Unfortunately I cannot save or apply anything even with new databases.

When I click on "OK" or "Apply" the application all of the sudden closes.

Also I cannot do "save as". Same issue. The application closes and nothing is inside the destination folder.

KeePassXC - 2.3.4
Revision: 6fe821c

Libraries:

Qt 5.9.7
libgcrypt 1.7.3
Operating system: Linux 4.19.13-300.fc29.x86_64
CPU architecture: x86_64
Kernel: 4.19.13-300.fc29.x86_64

Enabled extensions:

- Auto-Type
- Browser
- Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by fansari** [comment]
It is strange. Today it is working. Saving entries works again.

**Comment by fansari** [comment]
Now it happens again. I click "Apply" or "OK" and the application closes. The changes are not saved.

**Comment by Zlopez** [comment]
I had the same issue today, I found out that the application has segfault, because the name of the entry has whitespace in it. I removed the whitespace and the entry was saved without issue.

**Comment by AsavarTzeth** [comment]
@fansari I just tried creating a new database, including the `.kdbx` file extension explicitly and that worked.

I did some new research and this seems to be an issue specific to `xdg-desktop-portal-gtk`. I tried using `xdg-desktop-portal-kde` in which case it works as expected, with or without the `.kdbx` extension explicitly included.

See the referenced issue for more information.

**Comment by AsavarTzeth** [comment]
It is worth noting that the new 2.4.0 release includes a new database wizard that does append .kdbx to the default name in the filechooser. If a user removes it though it though it remains broken.

**Comment by AsavarTzeth** [comment]
I'm closing this issue in favour of https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191 and https://github.com/flatpak/xdg-desktop-portal/issues/496.
