### ISSUE TITLE
MIME type is not registered after installation

### ISSUE THREAD

**Issue by Ian2020** [flathub/org.keepassxc.KeePassXC#30]
The KeePass database MIME type is not registered during installation. One effect of this is that you cannot set the correct default app for KeePass database files in your desktop environment.

Expected behaviour:

Running `xdg-mime query filetype  <KEEPASS DATABASE FILE>` should return `application/x-keepass2`

Current behaviour:

Running `xdg-mime query filetype  <KEEPASS DATABASE FILE>` returns `application/octet-stream`

The user can fix this themselves with:

`xdg-mime install --novendor /var/lib/flatpak/app/org.keepassxc.KeePassXC/current/active/files/share/mime/packages/keepassxc.xml`

Could this be included in the automatic installation steps?

**Comment by AsavarTzeth** [comment]
To be honest, I do not know. I would guess that Flatpak can export mime types to the host. Perhaps it is as simple as renaming `keepassxc.xml` to `org.keepassxc.KeePassXC.xml` and it gets exported to the host?

Or am I missing something else? My understanding of mime types is very much limited to a user level.

I suppose I could make a quick attempt.

**Comment by AsavarTzeth** [comment]
Okay that was simple enough. I managed to get the expected output: `application/x-keepass2` with a test build. Stable builds are ongoing at this very moment.

Feel free to report back if it still does not work the way you expect it to.

**Comment by Ian2020** [comment]
Wow appreciate the fast response, thanks so much for fixing this!
