### ISSUE TITLE
"No QT platform plugin" error on 2019/02/19 release

### ISSUE THREAD

**Issue by britthouser** [flathub/org.keepassxc.KeePassXC#32]
I'm running F29 Silverblue (Version: 29.20190220.0) on my desktop.  Keepass had been working great until today.  Today, when I launch, I get the following error:

```
$ flatpak run org.keepassxc.KeePassXC
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

/app/bin/command-wrapper.sh: line 18:     3 Aborted                 keepassxc "$@"

```

If I set QT_QPA_PLATFORM=wayland and then launch, it will come up, but the mouse clicking is all messed up.  Keeps acting like I'm control-clicking or something like that.  If I revert to previous version (2019-01-22), then it works again.

**Comment by ykgmfq** [comment]
This happens on every GNOME Wayland session. Qt still relies on Xwayland on GNOME as of now. Please revert dcc39cc.

**Comment by AsavarTzeth** [comment]
I see. Sorry about that. I was confident I had tested this successfully, but clearly I missed something.

Will revert as soon as possible.
