### ISSUE TITLE
v2.4.0 does not open files under /run/user/ namespace

### ISSUE THREAD

**Issue by mat-m** [flathub/org.keepassxc.KeePassXC#34]
/run/user [is specified](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) as a runtime dir for storing temporary files in a user secured folder. On Linux Mint,  it is a tmpfs reached through fuse.
The AppImage of KeepassXC show the right path and has no issue opening and modifying the file.
The flatpak show the indirect name (#2) and tell us the file does not exist, although it found it since we were asked to type in the passphrase:

![image](https://user-images.githubusercontent.com/1039753/54873009-cc232300-4dcd-11e9-8c9a-b432fa1f8422.png)

**Comment by AsavarTzeth** [comment]
Actually that path is correct. It is where the [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) [Document portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Documents) mounts files you permit access to.

You should definitely be able to open it though. What does this command tell you?
```
flatpak document-list --columns=all
```

If that file is not in there, have you tried re-opening it (launching the file chooser)?

**Comment by topas-rec** [comment]
Definitely tried to reopen the file several times by file chooser and by double clicking the file.

**Comment by topas-rec** [comment]
> What is the output of this command?
flatpak document-list --columns=all

-- colunms seems to be an invalid option.
I see my file listed at the location on the file system. It is not listed at /run/user/.....

`8157445b	/mnt/DATA/Computers/private.kdbx`

Reopening the file through the file chooser does not add the file to the flatpak file list (in the path /run/user...)

What I see from the history file list in KeePassXC is that the hash changes with every opening of the file. So it is not constant:

![Screenshot from 2019-03-24 10-48-38](https://user-images.githubusercontent.com/20391449/54877724-8775a700-4e22-11e9-986c-0074c64b276d.png)

**Comment by topas-rec** [comment]
The hash that the app wants to open and the one in the file list of flatpak is the same.

`8157445b`

interesting

**Comment by AsavarTzeth** [comment]
I guess I am using a newer version of `flatpak`, which supports `--columns`.

Anyhow, that is very strange indeed. I have had no issues at all like this when I tested the build on my Arch Linux workstation.

So everything looks right, but the file is not added to `/run/user/UID/doc/`, as indicated? It seems like an issue with the document portal or in how the app interacts with it.
- What version of **xdg-desktop-portal** do you have installed?
- And just for the sake of it `flatpak --version`?

**Comment by GCamp6** [comment]
I have exactly the same issue in my LMDE.
I installed keepassXC from the app manager, if I try with the AppImage I can open the database.
 
```
flatpak --version
Flatpak 0.8.9
```

**Comment by AsavarTzeth** [comment]
@GCamp6 That is a pretty old version of Flatpak. I am more interested in **xdg-desktop-portal** though.

On Debian/Ubuntu I believe one universal method of getting that information from your package manager is:
```
dpkg-query --show xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-kde
```

**Comment by ykgmfq** [comment]
Ubuntu 18.04 has xdg-portal with version `0.11` and is affected.

**Comment by topas-rec** [comment]
> Just to clarify, you have verified that the file /run/user/1000/doc/8157445b/private.kdbx does not exist?

That file is there when the app is open and I used the open dialog to open the file from its original location.

**Comment by topas-rec** [comment]
Linux Mint 18:

> What version of xdg-desktop-portal do you have installed?

`dpkg-query --show xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-kde
xdg-desktop-portal	1.0.2-flatpak1~xenial
xdg-desktop-portal-gtk	1.0.2-flatpak1~xenial
dpkg-query: no packages found matching xdg-desktop-portal-kde`

> And just for the sake of it flatpak --version?

`flatpak --version
Flatpak 1.0.3`

**Comment by topas-rec** [comment]
Let me know if I can help and let me know how. (I have no clue how to find out the source of that problem)

**Comment by droidmonkey** [comment]
Based on some reviews in the Linux Mint store it looks like this started happening about 2 months ago.

**Comment by GCamp6** [comment]
My output of ` dpkg-query --show xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-kde
`
is

```
xdg-desktop-portal	0.5-1
xdg-desktop-portal-gtk	0.5-1
dpkg-query: no packages found matching xdg-desktop-portal-kde
```
and (I don't know if can be useful) the issue started after the last series of updates from the 22/03

![img](https://user-images.githubusercontent.com/9871274/54885353-89b81f80-4e7b-11e9-89e5-84ddfc5a07be.png)

**Comment by mahibi** [comment]
Had the same problem today. On https://forums.linuxmint.com/viewtopic.php?t=290743 @droidmonkey suggested to use AppImage or Snap. Thanks for the hint. Works fine after installing the Snap now!

**Comment by AsavarTzeth** [comment]
Honestly, I don't really have a clue either. At the very least I did manage to reproduce this, on Linux Mint and Arch Linux. As far as I can tell, KeePassXC does have access to the file but for whatever reason still complains about it.

Anyhow, at this point given the severity of this issue and a history of similar (but not identical) issues I just pushed a change giving full `--filesystem=host` access. Perhaps `--filesystem=home` would be enough for most people. If someone comes up with a better solution it can always be changed again.

Now that Flathub offers a beta branch I will let users opt in to test portal based file access in the **beta** branch instead. That solves all possible file access issues in one commit. It might be enought

*It is worth noting, that this is not strictly a Flatpak issue, but a portal related issue. Not that it matters, nor should it matter to end-users.*

*Disclaimer! I do not check anything on the "Mint Store", since I don't use it. Nor do I read those reviews. Mint just uses Flathub as their back-end remote.*

**Comment by droidmonkey** [comment]
@AsavarTzeth I was looking at your patch files for the app. Would you be ok if I directly incorporated them into KeePassXC? At least the flatpak build type and handling of install files.

**Comment by AsavarTzeth** [comment]
Actually I did rework those patches this week for that very purpose. Especially those first two. I would be honored if you merged them upstream.

I was planning a pull request, but if you can save me that time it would make me very happy.
