### ISSUE TITLE
Disable Software Update notifications

### ISSUE THREAD

**Issue by wjt** [flathub/org.keepassxc.KeePassXC#36]
KeePassXC has some functionality which checks with upstream for new versions:

![Screenshot from 2019-04-15 09-34-51](https://user-images.githubusercontent.com/86760/56118238-c1d5ee00-5f61-11e9-8f4c-0fb9dbcc7023.png)

The link points to https://keepassxc.org/download/ which does not offer a Flatpak download.

I suggest that this should either be disabled entirely, or should be reworked to monitor for the existence of `/app/.updated`, which is (re)created when a new version of the Flatpak has been installed, and prompt the user to restart in that case.

**Comment by AsavarTzeth** [comment]
Good idea. I do prefer your second suggestion, but simply hiding it could also suffice for now.
