### ISSUE TITLE
Window does not appear with AMD NAVI GPU

### ISSUE THREAD

**Issue by mikoim** [flathub/org.keepassxc.KeePassXC#43]
On AMD NAVI GPU, Mesa 19.2.0 doesn't work without LLVM 9. I guess that the runtime should upgrade their LLVM.
```bash
$ flatpak run org.keepassxc.KeePassXC
Warning: disregarding XDG_SESSION_TYPE=wayland
To use wayland anyway, please set QT_QPA_PLATFORM=wayland
Qt: Session management error: None of the authentication protocols specified are supported
radeonsi: Navi family support requires LLVM 9 or higher
```

**Comment by AsavarTzeth** [comment]
Well I did just bump the runtime to the latest version, so if anything it should contain newer versions than previously?

Anyhow, I believe I found an upstream issue:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/895

**Comment by mikoim** [comment]
## Workaround for NAVI users
```bash
sudo flatpak update --commit=bc774e2dfad7945122548b7b7c7517f97fd8233551b106f9a9bd83a39db5198e org.keepassxc.KeePassXC

flatpak run org.keepassxc.KeePassXC
```

**Comment by mikoim** [comment]
fixed in upstream
