### ISSUE TITLE
Flatpak app system tray icon doesn't work

### ISSUE THREAD

**Issue by alexbrrsclnt** [flathub/org.keepassxc.KeePassXC#5]
Select the checkbox to show the system tray icon has no effect. If I select any of the options to hide the app to the system tray when minified or instead of closing the window, neither appear to work.

**Comment by TingPing** [comment]
Does `flatpak run --talk-name=org.kde.StatusNotifierWatcher org.keepassxc.KeePassXC` work?

**Comment by alexbrrsclnt** [comment]
It works, but the system tray icon doesn't correspond to the app icon, an empty document icon is shown instead. Apart of this, the two options work as expected.

**Comment by TingPing** [comment]
It will probably need to be patched to use the right icon name.

**Comment by alexbrrsclnt** [comment]
One thing I have just notice, when I try to open and existing database, click the open button and the open dialog shows, my personal folder shows empty with no documents or folders. The filter to show only Keepass 2 databases is selected, but when I change to "all files" nothing changes, still no files.

Don't know if I must open a new issue for this.

**Comment by TingPing** [comment]
That is at least unrelated to this.

**Comment by AsavarTzeth** [comment]
I tested it on the latest plasma-desktop and tray icons seem to work as expected now.

**Comment by vasyugan** [comment]
For me it still does not work. On the console I see
failed to register service "org.kde.StatusNotifierItem-4-2
which sounds to me as if the flatpak kde platform is missing something that keepassxc wants.

**Comment by vasyugan** [comment]
> Does `flatpak run --talk-name=org.kde.StatusNotifierWatcher org.keepassxc.KeePassXC` work?

For me, it does not:

flatpak run --talk-name=org.kde.StatusNotifierWatcher org.keepassxc.KeePassXC
Warning: disregarding XDG_SESSION_TYPE=wayland
To use wayland anyway, please set QT_QPA_PLATFORM=wayland
failed to register service "org.kde.StatusNotifierItem-4-2"
QObject::startTimer: Timers cannot have negative intervals
