### ISSUE TITLE
Export command to run keepassxc-cli

### ISSUE THREAD

**Issue by Ian2020** [flathub/org.keepassxc.KeePassXC#50]
Thanks for your work packaging this as a flatpak. I am able to run the keepassxc-cli using

``` bash
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc-cli org.keepassxc.KeePassXC
```

However it would be neater if this was exported as a simple command `keepassxc-cli`. Is that possible with flatpak at the moment?

**Comment by TingPing** [comment]
No, applications can't "export" commands.
