### ISSUE TITLE
Latest org.keepassxc.KeePassXC can't remember column settings

### ISSUE THREAD

**Issue by ghost** [flathub/org.keepassxc.KeePassXC#54]
I need to hide every column one-by-one after every start. This issue appeared 1-2 weeks ago.

**Comment by corecontingency** [comment]
I cannot seem to replicate; Keepassxc remembers what columns I previously hid when I reopen it, even when opening a different database. Are you still having this issue?

**Comment by AsavarTzeth** [comment]
Neither can I. I sort of did once, but that seems to have been caused by me changing between test versions and resolved itself an additional app restart later.

**Comment by AsavarTzeth** [comment]
Closing, due to not being reproduced and no longer being valid after several app and runtime updates.

Please comment if the issue persists.
