### ISSUE TITLE
KeePassXC flatpak does not show system tray icon

### ISSUE THREAD

**Issue by TeamLinux01** [flathub/org.keepassxc.KeePassXC#58]
OS: Pop!_OS 20.04
Using gnome-extension "Ubuntu AppIndicators" for system tray icons.

The icon does not show up in the system tray area when the checkbox "Show a system tray icon" is checked.

I also had the same problem on Pop!_OS 19.10 with gnome-extension "KStatusNotifierItem/AppIndicator Support by 3v1n0" with the flatpak version.

No issues with the .deb or snap package.

**Comment by AsavarTzeth** [comment]
This should work as of 362a037832c2e653eb2bf98d75eaf352c17ca3c3 which is included with the update to 2.6.0.

Please test it to the best of your ability. If you're interested in the details of this change as well as it's limitations feel free to read the commit message.

**Comment by TeamLinux01** [comment]
I updated to the latest version (2.6.0) and if I launch it from the icon, it does not provide a tray icon.
If I launch it from the terminal (flatpakrun org.keepassxc.KeePassXC) I do get the tray icon, so it might be a problem with Pop!_OS at this point and not KeePassXC.

Thank you.

**Comment by darkdragon-001** [comment]
> I updated to the latest version (2.6.0) and if I launch it from the icon, it does not provide a tray icon.
> If I launch it from the terminal (flatpak run org.keepassxc.KeePassXC) I do get the tray icon, so it might be a problem with Pop!_OS at this point and not KeePassXC.

Same on Ubuntu 20.04.

**Comment by darkdragon-001** [comment]
I checked the command line from the desktop file `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc --file-forwarding org.keepassxc.KeePassXC` which also does not show the icon. Removing `--command=keepassxc` shows the icon.

**Comment by TeamLinux01** [comment]
> I checked the command line from the desktop file `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc --file-forwarding org.keepassxc.KeePassXC` which also does not show the icon. Removing `--command=keepassxc` shows the icon.

I also just removed `--command=keepassxc` and it now displays the tray icon when launching from the shortcut icon.

**Comment by AsavarTzeth** [comment]
That's odd. I have never noticed that the command is `keepassxc` in the desktop file. I would expect it to be `keepassxc-wrapper`, as set in [the manifest](https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/org.keepassxc.KeePassXC.yml#L5).

The difference is if the wrapper script is run or not, which of course affects the value of the pid. In this case (and I confirmed this) that means `org.kde.StatusNotifierItem-2-2` is used instead which I haven't allowed, because I choose more restrictive permissions.

I suppose I can just allow that as well, which should cover both cases, wrapper or no wrapper. But still I wonder why flatpak doesn't honour the manifest?

**Comment by penyuan** [comment]
Just tested, I can confirm that I get the system tray icon if I start from command line:

```
> flatpak run org.keepassxc.KeePassXC
```

However, if I start from the .desktop file, I don't get the system tray icon. This is true in Wayland and Xorg mode.

Not sure if this matters, but here is the full output from starting the Flatpak from the commandlind:

```
> flatpak run org.keepassxc.KeePassXC
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by AsavarTzeth** [comment]
There are test builds are available in the new pull request. I would appreciate it if anyone of you tested those instead. At this point I am well aware of the issue in the current stable.

@TeamLinux01 @darkdragon-001 *By the way substituting `--command=keepassxc` with `--command=keepassxc-wrapper` instead of removing it should also work, correct? I guess removing it forces flatpak to use the command specified in the manifest, or it wouldn't have anything at all to go by.*

**Comment by darkdragon-001** [comment]
@AsavarTzeth I can confirm that both, substituting `--command` and running your PR work independently.

**Comment by AsavarTzeth** [comment]
Great! My assumptions seem to have worked out this time.

Thank you again. The fact that you considered tried removing `--command=keepassxc` in the first place greatly helped me in figuring out the real cause, and quickly too.

**Comment by TeamLinux01** [comment]
The new version does seem to be working as intended now.

Thank you very much for working on this.
