### ISSUE TITLE
'Create' or 'open' database does nothing (unable to open file browser

### ISSUE THREAD

**Issue by ysteina** [flathub/org.keepassxc.KeePassXC#6]
Distro: KDE Neon 5.12.1
Flatpak from alexlarsson ppa
Downloaded flatpakref for keepassxc from flathub

Title says it all. After install, opening keepassxc starts the program but if I click 'open database', 'create database' or 'import database' nothing seems to happen.

**Comment by AsavarTzeth** [comment]
To me it sounds like the same issues as in #1. Although that issue was fixed in the kde runtime and I have not experienced it since (still don't).

Just in case I have to ask, is your `org.kde.Platform` up-to-date? You can verify with:

    flatpak info org.kde.Plaform

**Comment by nedrichards** [comment]
Which exact version of flatpak and xdg-desktop-portals do you have? You need either 0.10.4 or 0.11.1 and 0.10 respectively for some fixes with the documents portals and KDE.

**Comment by ysteina** [comment]
Flatpak 0.11.1
xdg-desktop-portal 0.10-0

`Ref: runtime/org.kde.Platform/x86_64/5.9
ID: org.kde.Platform
Arch: x86_64
Branch: 5.9
Origin: flathub
Date: 2018-02-12 14:47:37 +0000
Subject: Fix syntax (66f7184a)
Commit: ea891f4a918fe3f17df3a94dd78f9c8172c9bce9a14311dd6400dcb37cd0b8b9
Parent: 6bcc5bc1665c806fc259ff5e32e10d997ea9caefd4afb4a28b3e87d399f4f715
Location: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.9/ea891f4a918fe3f17df3a94dd78f9c8172c9bce9a14311dd6400dcb37cd0b8b9
Installed size: 1,1 GB
`

**Comment by ysteina** [comment]
It works now! I removed the app two weeks ago but reinstalled it yesterday and the file browser now works as expected.

**Comment by AsavarTzeth** [comment]
Interesting timing, I am about to update to KeePassXC 2.3.0.

I assume some update to `flatpak`, `xdg-desktop-portals` or the `org.kde.Platform` update fixed the issue. Since you don't experience the issue anymore I'm closing this for now.
