### ISSUE TITLE
Keepass keeps opening when closing browser

### ISSUE THREAD

**Issue by mannotserious** [flathub/org.keepassxc.KeePassXC#65]
**KeepassXC will maximize every time I close any browser, regardless of settings changed.**

KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Flatpak

Qt 5.14.2
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.4.0-7634-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by AsavarTzeth** [comment]
Are all of your browsers truly closed? This behaviour has always existed, once you launch a browser and there isn't anything that can be done about it. It is a consequence of the browser extension executing the flatpak.

However once all browsers are closed you should be able to close KeePassXC without it reappearing.

**Comment by AsavarTzeth** [comment]
While I can't claim this issue is entirely fixed or that I know why it occurs in the first place it does seem less frequent now, perhaps because I now use `exec` in the wrapper script.

@mannotserious Are there any noticeable changes in your case?
