### ISSUE TITLE
misleading version number on flathub.org

### ISSUE THREAD

**Issue by gkiagia** [flathub/org.keepassxc.KeePassXC#68]
https://flathub.org/apps/details/org.keepassxc.KeePassXC says that the distributed version is 2.5.4, while in fact it's 2.6.0

**Comment by AsavarTzeth** [comment]
Yeah I noticed that just now, when I was about to look into version 2.6.1. Hopefully it will be solved by itself in that process, but if not I will look into it.

**Comment by AsavarTzeth** [comment]
Hmm, it seems upstream screwed that one up?
https://github.com/keepassxreboot/keepassxc/blob/2.6.0/share/linux/org.keepassxc.KeePassXC.appdata.xml#L53-L57

Obviously the latest release can't be backwards in time.

And yes, 2.6.1 has fixed this:
https://github.com/keepassxreboot/keepassxc/blob/2.6.1/share/linux/org.keepassxc.KeePassXC.appdata.xml

**Comment by AsavarTzeth** [comment]
Fixed!
