### ISSUE TITLE
Qt: Session management error: None of the authentication protocols specified are supported

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.keepassxc.KeePassXC#7]

**Comment by AsavarTzeth** [comment]
Are you experiencing any visible issues with the **org.keepassxc.KeePassXC** flatpak in relation to this error message? If that's the case you would need to provide more information.

The error message has something to do with session management and might or might not occur depending on the desktop environment. For example: I can see this error under my gnome-shell session, but not if I start a plasma session.

As far as I can tell it can safely be ignored.
