### ISSUE TITLE
Flatpak Keepassxc is causing the Deepin V20 1003 "system" to crash when executed.

### ISSUE THREAD

**Issue by serial02** [flathub/org.keepassxc.KeePassXC#72]
Hello Team Keepass

Flatpak Keepassxc is causing the Deepin V20 1003 "system" to crash when executed.

The PC can only be turned off using the disconnect button after this lockout.
I believe it is raising the CPU to 100%.

I just formatted an HD with Deepin V20 updated with version 1003 precisely because of this problem.
I performed a clean installation and installed one application at a time until I found out who was causing this crash.

I only removed the keepassxc package (flatpak removes org.keepassxc.KeePassXC), but I left the KDE aggregates.
If need to remove KDE as well, tell me the command.

![WhatsApp Image 2020-11-02 at 02 54 41](https://user-images.githubusercontent.com/32621790/97836398-fed81180-1cba-11eb-96a7-2e7a36e8c4aa.jpeg)

Your considerations

Serial

**Comment by AsavarTzeth** [comment]
I am not a part of either the Flatpak or KeePassXC team. I am just a simple package maintainer that contributes to Flathub, and one with very limited time at the moment. That being said:

That sounds serious. I would report it to flatpak developers as well. Unfortunately there isn't much I can help you with, based on a few assumptions alone. I would need some debugging on your end.

- Do you know if your desktop is using Wayland or Xorg?
- Does it make any difference if you run `flatpak run --env=QT_QPA_PLATFORM=xcb org.keepassxc.KeePassXC`

**Comment by AsavarTzeth** [comment]
Regarding those KDE "aggregates". Those are flatpak runtimes and extensions, or in other words application dependencies.

- `org.kde.Platform` is the only real dependency, is required to run the app and is shared by other flatpaks.
- `org.kde.Platform.Locale` contains translations in your chosen languages, for the above.
- `org.kde.KStyle.Adwaita` ensures the app respects the style of your gtk based desktop.

You may remove anything that no longer is in use with `flatpak uninstall --unused`.

**Comment by serial02** [comment]
Hello @AsavarTzeth 

The problem was resolved with the latest update to Deepin V20.1 1005-Beta, as seen here:

https://discourse.flathub.org/t/flatpak-keepassxc-is-causing-the-deepin-v20-1003-system-to-crash-when-executed/877/5

Thank You

**Comment by AsavarTzeth** [comment]
Oh! That makes me so happy. Thank you for sharing :+1:
