### ISSUE TITLE
Enable Secret Storage support

### ISSUE THREAD

**Issue by runiq** [flathub/org.keepassxc.KeePassXC#73]
Hi, thanks for packaging this! <3

I wanted to use the secretstorage integration, but it looks like it's not compiled in:

```
$ flatpak run --env=LC_ALL=C org.keepassxc.KeePassXC --debug-info
KeePassXC - Version 2.6.2
Revision: e9b9582
Distribution: Flatpak

Qt 5.15.1
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.9.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.7
```

It's missing "Secret Service Integration" from the list of extensions currently. Is that expected? I've looked through the issues but have failed to turn up a reason why.

**Comment by AsavarTzeth** [comment]
That is on purpose, because it will not work. Try searching the commit history. I usually describe every change I do in detail.

**Comment by AsavarTzeth** [comment]
On second thought. Here you go: https://github.com/flathub/org.keepassxc.KeePassXC/commit/79b8f9e9c558f5cf63a6444c531bf141febaaf6f

**Comment by runiq** [comment]
Oh wow, there's much more to that than I had expected. I definitely appreciate the thought behind that decision!

Still, the secret service integration is off by default, even if it's compiled in. How about compiling it in, but *not* letting the app own org.freedesktop.secrets? Then using KPXCs secretservice impl would still be gated behind a `flatpak override`.

**Comment by AsavarTzeth** [comment]
Indeed, I am just now rediscovering all of the issues. As past me noted, it really breaks things. Worse, the language in the app could sort of encourage the user (unintentionally, of course) to do so. Which is not to say that tinkering is bad, but inexperienced people losing passwords is not something I wish to encourage.

_Also, to be truthful, I am a bit hesitant at enabling it when I am sure that once it is visible in the options (especially after having been invisible) someone will expect it to work. Unlike you they might not even try to read old issues._

In principle your suggestion is acceptable. However after having tried it with Epiphany (Arch Linux package) and seahorse (Arch and flatpak) I found that it does not work. Although it does register the `org.freedesktop.secrets` service correctly.

That being said. If you or anyone finds a way to make it work (albeit local configuration required) I could consider compiling it. As for the visibility by default: I'm not actively using the beta branch. Perhaps that would be a solution?

**Comment by AsavarTzeth** [comment]
For the sake of reference, I might as well make a second attempt at a quick but clear compilation of all issues:

- Requires ownership of `org.freedesktop.secrets`
  + Does not appear to work, despite ownership of the secrets service
- Will not be DBus activatable
  + Does not install any DBus service file: `org.freedesktop.secrets.service`
  + Isn't allowed to export files that doesn't match the app id (or does `--own-name` override that too?)
- Does not work as a full replacement for `gnome-keyring`
  + Does not implement a secrets portal backend
  + Conflicts with the `gnome-keyring` implementation, requiring `gnome-keyring` to be disabled
  + Disabling `gnome-keyring` will break apps that depend on the portal storage
  + Breakage could in a worst case scenario lead to lost passwords

If we find more I can simply edit the list. Same applies if a workaround is found.

**Comment by pigsflew** [comment]
Correction: The DBUS interfaces are on `org.freedesktop.Secret.*`, not plural! ([Freedesktop Spec](https://specifications.freedesktop.org/secret-service/latest/ch13.html))

So long as you're not actually trying to replace `gnome-keyring`, but are simply trying to provide access to secrets in an unlocked database via DBUS, we really *should* only need `talks` access, right?

I'd love to see this plugin activated, it'd really help me with integrating across the system. Maybe there could be a separate flatpak with secretservice enabled?

**Comment by pigsflew** [comment]
I may be able to try this out this weekend.

**Comment by faan11** [comment]
any news about this issue?

**Comment by pm4rcin** [comment]
@AsavarTzeth do I only need to change the config option and give `org.freedesktop.Secret.*` dbus access and that should be it?

**Comment by marzzzello** [comment]
I build the flatpak with the build flag enabled and I added `- --own-name=org.freedesktop.secrets` to `finish-args:`
I tested it with Evolution and some other apps and they worked fine. The notification doesn't show the name of the clients. It just says `1 Entry was used by unkown executable (DBus address :1.647)`. `org.freedesktop.Secret.*` is not needed I think.

```diff
diff --git a/org.keepassxc.KeePassXC.yml b/org.keepassxc.KeePassXC.yml
index 68e02ae..2968286 100644
--- a/org.keepassxc.KeePassXC.yml
+++ b/org.keepassxc.KeePassXC.yml
@@ -24,6 +24,8 @@ finish-args:
   - --own-name=org.kde.StatusNotifierItem-2-1 # Especially test these
   - --own-name=org.kde.StatusNotifierItem-2-2
   - --own-name=org.kde.StatusNotifierItem-3-2
+    # Secret Service
+  - --own-name=org.freedesktop.secrets
     # Favicon Download
   - --share=network
     # YubiKey USB access
@@ -61,14 +63,8 @@ modules:
       - -DKEEPASSXC_BUILD_TYPE=Release
       - -DWITH_TESTS=OFF
       - -DCMAKE_INSTALL_LIBDIR=lib
+      - -DWITH_XC_ALL=ON
       - -DWITH_XC_UPDATECHECK=OFF
-      - -DWITH_XC_AUTOTYPE=ON
-      - -DWITH_XC_NETWORKING=ON
-      - -DWITH_XC_BROWSER=ON
-      - -DWITH_XC_YUBIKEY=ON
-      - -DWITH_XC_SSHAGENT=ON
-      - -DWITH_XC_KEESHARE=ON
-      - -DWITH_XC_FDOSECRETS=OFF
     sources:
       - type: archive
         url: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.1/keepassxc-2.7.1-src.tar.xz
```

**Comment by pm4rcin** [comment]
> I build the flatpak with the build flag enabled and I added `- --own-name=org.freedesktop.secrets` to `finish-args:` I tested it with Evolution and some other apps and they worked fine. The notification doesn't show the name of the clients. It just says `1 Entry was used by unkown executable (DBus address :1.647)`. `org.freedesktop.Secret.*` is not needed I think.
> 
> ```diff
> diff --git a/org.keepassxc.KeePassXC.yml b/org.keepassxc.KeePassXC.yml
> index 68e02ae..2968286 100644
> --- a/org.keepassxc.KeePassXC.yml
> +++ b/org.keepassxc.KeePassXC.yml
> @@ -24,6 +24,8 @@ finish-args:
>    - --own-name=org.kde.StatusNotifierItem-2-1 # Especially test these
>    - --own-name=org.kde.StatusNotifierItem-2-2
>    - --own-name=org.kde.StatusNotifierItem-3-2
> +    # Secret Service
> +  - --own-name=org.freedesktop.secrets
>      # Favicon Download
>    - --share=network
>      # YubiKey USB access
> @@ -61,14 +63,8 @@ modules:
>        - -DKEEPASSXC_BUILD_TYPE=Release
>        - -DWITH_TESTS=OFF
>        - -DCMAKE_INSTALL_LIBDIR=lib
> +      - -DWITH_XC_ALL=ON
>        - -DWITH_XC_UPDATECHECK=OFF
> -      - -DWITH_XC_AUTOTYPE=ON
> -      - -DWITH_XC_NETWORKING=ON
> -      - -DWITH_XC_BROWSER=ON
> -      - -DWITH_XC_YUBIKEY=ON
> -      - -DWITH_XC_SSHAGENT=ON
> -      - -DWITH_XC_KEESHARE=ON
> -      - -DWITH_XC_FDOSECRETS=OFF
>      sources:
>        - type: archive
>          url: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.1/keepassxc-2.7.1-src.tar.xz
> ```

`org.freedesktop.Secret.*` is needed instead of `org.freedesktop.secrets` because it's in the Dbus reference. That may be the reason why you see the strange notification instead of proper one. Try to change it and see how it works.

**Comment by marzzzello** [comment]
I tried `org.freedesktop.Secret.*` but when I wanted to enable the secret service of keepassxc it didn't work. It said it can't access org.freedesktop.secrets and that it's maybe used by another program

**Comment by pm4rcin** [comment]
I've looked around a bit and looks like it's not fully ready in portal if I understand correctly. https://github.com/keepassxreboot/keepassxc/issues/6274#issuecomment-826083122

**Comment by marzzzello** [comment]
I don't need this in my use case. I don't see why gnome-keyring needs to be installed, maybe it's different for Ubuntu. I use Arch btw.
The changes I described above are everything that is needed to make it work. Program names in notifications are not that important to me

**Comment by StayPirate** [comment]
I've been using KPXC for many years and for a couple of years it's been my default secret service provider. I installed KPXC via flatpak for the first time yesterday, and I'm now very disappointed on seeing that it's not compiled without the secret service integration. I am tempted to re-installed via the OS package manager, but I first want to try the re-compile following [the indication](https://github.com/flathub/org.keepassxc.KeePassXC/issues/73#issuecomment-1255319091) from @marzzzello.

In the meantime I'd like to ask to @AsavarTzeth if he can reconsider his position, 2y+ passed since your last update and it seems that other people already managed to make it work properly. Can this now be included in the flatpaked KPXC?
