### ISSUE TITLE
.tor-browser directory created on every KeePassXC start

### ISSUE THREAD

**Issue by martinfischer** [flathub/org.keepassxc.KeePassXC#74]
I am not using Tor Browser and the KeePassXC Browser Integration is deactivated, yet every time I start the app a .tor-browser directory is created in my home directory. If I remove it, a KeePassXC start will create it again.

I don't think this should be happening as I cannot find any other setting to turn this behaviour off.

**Comment by AsavarTzeth** [comment]
Fixed in https://github.com/flathub/org.keepassxc.KeePassXC/commit/ea245835bf89236272f32864324cd5e68265b05d.
