### ISSUE TITLE
Clipboard not working on Wayland mode

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.keepassxc.KeePassXC#8]
When running from `flatpak run --env=GDK_BACKEND=wayland --env=QT_QPA_PLATFORM=wayland --socket=wayland --nosocket=x11 org.keepassxc.KeePassXC` the clipboard doesn't work. I don't know whether it is a problem of Qt or a problem of KeePassXC

**Comment by TingPing** [comment]
Surely its not a problem with the Flatpak though and should be reported upstream?

**Comment by amtlib-dot-dll** [comment]
Well @AsavarTzeth sorry to bother you but are you a member of the upstream? Since you created this repo

**Comment by AsavarTzeth** [comment]
No, I am not a member of upstream KeePassXC team, if that's what your asking. I would still consider myself a contributing upstream community member though.

About the issue; on the surface this sounds like a wayland issue to me. Specifically it reminds me of back when certain compositors had no way of sharing X11 and wayland clipboards.

Some troubleshooting steps I would start with:

- What wayland compositor is in use?
- Is this reproducible with other wayland compositors?
- Is the clipboard not working at all, or is it simply limited to other wayland capable applications?

**Comment by amtlib-dot-dll** [comment]
Thank you for enlighten me. I cannot copy my username to an Electron application (using XWayland), but I can copy it to pure Wayland applications. I am using Fedora 27 and the compositor version is `mutter-3.26.2-2.fc27.x86_64` and the XWayland version is `xorg-x11-server-Xwayland-1.19.6-5.fc27.x86_64`

**Comment by amtlib-dot-dll** [comment]
Update: It appears that the clipboard is OK inside this application, but when I switched out to paste my password to my browser, the clipboard is cleared globally. Perhaps we should check any code relative to the window switching.

**Comment by AsavarTzeth** [comment]
Is this still an issue? Was it ever reported upstream?

**Comment by amtlib-dot-dll** [comment]
Still an issue

**Comment by penyuan** [comment]
> Update: It appears that the clipboard is OK inside this application, but when I switched out to paste my password to my browser, the clipboard is cleared globally. Perhaps we should check any code relative to the window switching.

This is also the symptom for me. I cannot copy something from within KeepassXC (Flatpak) to my web browser (non-Flatpak). I am running Gnome 3.32.2 on RHEL 8.1 which I believe is Wayland by default.

Any idea for possible solutions or workaround? Thanks for looking into this.

**Comment by lightonflux** [comment]
I cannot copy something into KeepassXC (Flathub). Can you confirm that this is the case? (E.g. Copying into the password or note field)

**Comment by penyuan** [comment]
> I cannot copy something into KeepassXC (Flathub). Can you confirm that this is the case? (E.g. Copying into the password or note field)

I can confirm.

> Works under X.org

I changed my Gnome to X-mode (instead of Wayland), and now bi-directional copy and paste works! So looks like a Wayland problem, indeed. How do we solve this?

**Comment by lightonflux** [comment]
@penyuan please go into your wayland session, download the official appimage [1] run it and test if the issue is present. I will do the same. Then we know if this is an upstream or flatpak issue.

1: https://keepassxc.org/download/#linux

**Comment by lightonflux** [comment]
Here my test:
1. Login as wayland session (Gnome 3.36 on Fedora 32)
1. Double check by getting your session ID and checking the session type
1. Start AppImage in Terminal
1. Create new entry by pasting a bunch of strings
1. Does it work?

Terminal output
```
ws :: ~ » loginctl                        
SESSION  UID USER   SEAT  TTY 
     12 1000 lightonflux seat0 tty2

1 sessions listed.
ws :: ~ » loginctl show-session 12 -p Type
Type=wayland
ws :: ~ » cd Downloads 
ws :: ~/Downloads » ./KeePassXC-2.5.4-x86_64.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by lightonflux** [comment]
The test results are weird. 
Testing in the AppImage worked. I could copy and paste without any issue.
But then i closed the AppImage Instance and started the Flatpak. After this i create a new entry, manually entered a login name. And the paste stuff successfully into password, note and so on.

BUT then i closed the flatpak again. Started it a second time and the issue reappeared. I was not able to paste into the password or notes field. (I also wrote something manually into login like before).

**Comment by lightonflux** [comment]
To clarify. I use the flatpak with version 2.5.4 just like the AppImage.

**Comment by penyuan** [comment]
> @penyuan please go into your wayland session, download the official appimage [1] run it and test if the issue is present. I will do the same. Then we know if this is an upstream or flatpak issue.
> 
> 1: https://keepassxc.org/download/#linux

OK. I re-activated Gnome in Wayland mode. Here's what I found:

1. Official Appimage works fine, no problem with bi-directional copy and paste.

2. With the Flatpak, I can't copy from KeepassXC to anything outside. However, I can copy things from other applications *into* KeepassXC. Strange!!

BTW, for the life of me I can't get the tray icon to appear. I am running Gnome 3.32.2 with system tray extensions. Other tray icons such as from the Skype Flatpak show up, but not for KeepassXC flatpak with or without Wayland activated. Not sure if this is related, maybe this should be a separate issue?

**Comment by darkdragon-001** [comment]
Is this still an issue in 2.6.0 (#60)? According to the [release notes](https://keepassxc.org/blog/2020-07-07-2.6.0-released/) `wl-clipboard` is used if `xclip` is not available.

**Comment by penyuan** [comment]
> Is this still an issue in 2.6.0 (#60)? According to the [release notes](https://keepassxc.org/blog/2020-07-07-2.6.0-released/) `wl-clipboard` is used if `xclip` is not available.

The Flatpak provided [on Flathub](https://flathub.org/apps/details/org.keepassxc.KeePassXC) is still on version 2.5.4. I will be happy to test this once the Flatpak has been updated to the latest 2.6.0 release.

**Comment by AsavarTzeth** [comment]
@penyuan Version 2.6.0 should be available now or sometime very soon.

For future reference: there are automatic test builds linked to in pull requests.

**Comment by penyuan** [comment]
> @penyuan Version 2.6.0 should be available now or sometime very soon.
> 
> For future reference: there are automatic test builds linked to in pull requests.

Just installed it and tried it in Wayland and Xorg mode for completeness. Here's what I found:

1. Bidirectional clipboard using the mouse now works! :+1: Strangely, I can use Ctrl+C to copy things *from* KeePassXC in Xorg mode, but *not* in Wayland mode. Other cut/copy/paste behaviour looks OK.
2. Still no system tray icon in both Wayland and Xorg mode.
3. **New issue:** My display is low resolution at 1366x768. The KeepassXC window takes up most of the screen, and for some reason menus opened from the menu bar open **upwards** above the window and get cut off by the end of my screen. Why is this? Is a separate issue warranted?

Anyway, thank you for your help!

**Comment by darkdragon-001** [comment]
> 2. Still no system tray icon in both Wayland and Xorg mode.

See #58.

**Comment by penyuan** [comment]
> > 1. Still no system tray icon in both Wayland and Xorg mode.
> 
> See #58.

Thank you. I have posted my test results there.

**Comment by AsavarTzeth** [comment]
@penyuan In this issue I specifically ask whether anyone still experiences a partially working or plain broken clipboard in a wayland session. Arbitrary output from the command line unfortunately doesn't tell me anything about that.

**Comment by AsavarTzeth** [comment]
@penyuan Thank you! Nice to hear that bidirectional clipboards work now!

Your second issue has its own existing issue thread, and I see you found it.

About your third issue. I very much doubt it has anything to do with Flatpak or in any case that there is anything I can do about it at this level. Personally I have no clue what is causing it.

*Sorry if you read my earlier (deleted) comment and it confused you. I'm clearly a tad tired :) *

**Comment by penyuan** [comment]
> Nice to hear that bidirectional clipboards work now!

Sorry to be a pain, but I am sad to report that apparently bi-directional clipboard behaviour under Wayland is actually very erratic. My previous report was just based on my initial test, but over the past week I discovered that I often have to switch between KeePassXC and the target window (I tried Firefox 78.0.2 and Gnome's stock text editor) and re-try copy-pasting *5-6* times before the copy (from KeePassXC) is registered and carries over!

One small clue is that when I copy something in KeePassXC, there they "Paste" option in the context menu of the target program is greyed out, which to be suggests that nothing made it to the clipboard.

This is bizarre, and I honestly don't know how to get to the root of this problem... :disappointed: Can anyone advise?

**Comment by Ezwen** [comment]
Using Fedora 33 the clipboard indeed does not work currently with this flatpak. Really stange.

**Comment by AsavarTzeth** [comment]
@Ezwen Interesting I had to do that to even get KeePassXC to launch on my laptop if I run Gnome Shell's X session instead of Wayland. In my case it also seems to be caused by an incorrect qpa plugin:

```
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

Is it possible the commonality here is broken platform plugin detection/selection? Perhaps some plugins work with clipboards and other doesn't?

If say platform plugins would change randomly, even during the same desktop session that might explain why things have randomly stopped working.

**Comment by AsavarTzeth** [comment]
I decided to try forcing X/Xwayland by setting `QT_QPA_PLATFORM=xcb`. If I push that it means native wayland will never be used by default out of the box. Users would have to use overrides to force that.

Then again it might be wiser to have it work well at all out of the box and let those that care to run it natively (like me) use overrides.

My own testing reveals that clipboard support doesn't seem worse. I can't tell because on my systems it works either way, or maybe its just that I almost only run apps under wayland.

**Comment by Frankstar** [comment]
we have similiar/same Problem in ksnip.
https://github.com/ksnip/ksnip/issues/416

mayb it helps you finding the right solution ...
