### ISSUE TITLE
Fix remote shares access with GVFS 1.48

### ISSUE THREAD

**Issue by x80486** [flathub/org.keepassxc.KeePassXC#80]
Reference: https://github.com/flathub/flathub/issues/2180

**Comment by hadess** [comment]
Not sure that KeePassXC needs to talk to gvfs to work properly.

**Comment by droidmonkey** [comment]
This is solved in 2.7.x using "Direct-write Saves". Read the user guide for more information

**Comment by hadess** [comment]
> This is solved in 2.7.x using "Direct-write Saves". Read the user guide for more information

I'm pretty sure this isn't relevant to this issue. The manifest still has mentions of open permissions to talk to D-Bus names that don't exist. See the docs here:
https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access

**Comment by droidmonkey** [comment]
True but we already have the gvfs access request in the manifest. Direct write saves are necessary to use it correctly. https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/org.keepassxc.KeePassXC.yml#L45

**Comment by hadess** [comment]
> True but we already have the gvfs access request in the manifest. Direct write saves are necessary to use it correctly. https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/org.keepassxc.KeePassXC.yml#L45

Can you please read the documentation I pointed to, especially the two sections that say:
> --talk-name=org.gtk.vfs.* is necessary to talk to the gvfs daemons over D-Bus and list mounts using the GIO APIs.

which your application doesn't use.

And:
> No application should be using --talk-name=org.gtk.vfs in its manifest, as there are no D-Bus services named org.gtk.vfs.

which appears in your manifest despite doing nothing.

**Comment by droidmonkey** [comment]
Read the documentation closely, only gtk and gnome apps need to speak to dbus. We can remove both from the manifest but there inclusion doesn't matter.

**Comment by hadess** [comment]
> Read the documentation closely, only gtk and gnome apps need to speak to dbus. We can remove both from the manifest but there inclusion doesn't matter.

Removing those 2 unused stanzas from the manifest is what's been requested since March last year.

**Comment by hadess** [comment]
The documentation in question mentions what to do for saving to gvfs shares[1]:
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_save_options

However the original comment, and the linked issue, are about removing unused gvfs-related permissions, and making sure that those used are correct.

[1]: whether a path is gvfs could actually be detected automatically by checking the scheme of the URI that we get from the path:
```c
// gcc -o foo `pkg-config --libs --cflags gio-2.0` foo.c
#include <gio/gio.h>

int main (int argc, char **argv)
{
        if (argc != 2) {
                g_print ("Usage: %s PATH\n", argv[0]);
                return 1;
        }

        GFile *file = g_file_new_for_path (argv[1]);
        char *uri = g_file_get_uri (file);
        g_print ("URI is: %s\n", uri);
        char *scheme = g_file_get_uri_scheme (file);
        g_print ("scheme is: %s\n", scheme);

        return 0;
}
```

```sh
$ gcc -o foo `pkg-config --libs --cflags gio-2.0` foo.c
$ ./foo '/run/user/1000/gvfs/smb-share:server=diskstation.local,share=user/foo.zip' 
URI is: smb://diskstation.local/user/foo.zip
scheme is: smb
```

**Comment by hadess** [comment]
> However the original comment, and the linked issue, are about removing unused gvfs-related permissions, and making sure that those used are correct.

PR opened as https://github.com/flathub/org.keepassxc.KeePassXC/pull/95 as this still isn't fixed.
