### ISSUE TITLE
"Automatically launch KeePassXC at system startup" is not working

### ISSUE THREAD

**Issue by soredake** [flathub/org.keepassxc.KeePassXC#81]
Nothing is created in `~/.config/autostart`, Kubuntu 21.04

**Comment by vchernin** [comment]
It needs background portal support

**Comment by droidmonkey** [comment]
Confirmed still broken

**Comment by vchernin** [comment]
Some links:

https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background
https://libportal.org/method.Portal.request_background.html

Note the background portal is a bit broken in xdg-desktop-portal 1.14.3: https://github.com/flatpak/xdg-desktop-portal/pull/778 (1.12.x should be fine though)

**Comment by GeorgesStavracas** [comment]
There'll be an xdg-desktop-portal release soon that should fix this
