### ISSUE TITLE
2.7.0 has been released

### ISSUE THREAD

**Issue by fossrob** [flathub/org.keepassxc.KeePassXC#87]
I'm sorry if this is not the way to do this but I saw previously [there was an issue opened for 2.6.0](https://github.com/flathub/org.keepassxc.KeePassXC/issues/60) 😊 

Github release link: https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0
Annoucement link: https://keepassxc.org/blog/2022-03-21-2.7.0-released/

**Comment by joelchrono12** [comment]
why is this still not updated yet? :cry:

**Comment by AzureRaptor** [comment]
Is there anything we as users can do to help, i.e. do you need feedback on an "unstable" channel (forgive me, not very familiar with flatpak and only a little with snap) or some other testing situation?  I'd be happy to help if I could.

**Comment by rocketraman** [comment]
This is probably the best place to follow now: https://github.com/flathub/org.keepassxc.KeePassXC/pull/89.

**Comment by droidmonkey** [comment]
Help us test: `flatpak install https://flathub.org/beta-repo/appstream/org.keepassxc.KeePassXC.flatpakref`

**Comment by rocketraman** [comment]
> Help us test: `flatpak install https://flathub.org/beta-repo/appstream/org.keepassxc.KeePassXC.flatpakref`

@droidmonkey That command installs KeepassXC 2.5.2?

**Comment by droidmonkey** [comment]
Yah sorry the beta flethub seems broken, here is the direct build link: https://dl.flathub.org/build-repo/83196/org.keepassxc.KeePassXC.flatpakref

**Comment by rocketraman** [comment]
It did update to 2.7.1 from the beta repo now. So far so good!

**Comment by droidmonkey** [comment]
2.7.1 FlatHub has been released to the world!
