### ISSUE TITLE
Application starts on browser launch

### ISSUE THREAD

**Issue by droidmonkey** [flathub/org.keepassxc.KeePassXC#94]
## Overview
KeepassXC starts on browser launch with extension enabled. This happens every time after computer boots.

## Steps to Reproduce
1. Enable browser extension.
2. Enable browser integration.
3. Reboot PC.
4. Start web browser.

## Expected Behavior
KeePassXC should not open when web browser is opened after a system boot.

## Actual Behavior
Every time after a system boot, when the web browser is opened for the first time, KeePassXC opens one time.

## Context

The native host runner points to: `/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC` 

But this is the parameter that's missing (which is why KeePassXC UI keeps opening):

`--command=keepassxc-proxy`

I fixed this by making a second script: `/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC.proxy`

This is what is in the script:

`#!/bin/sh
exec /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc-proxy org.keepassxc.KeePassXC "$@"`

Then I pointed native host runner to: `/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC.proxy`

This fixes the issue. But if this can be added for the next release, that would be great.

KeePassXC - 2.7.1
Revision: 5916a8f
Distribution: Flatpak

Operating System: Ubuntu 20.04
Desktop Env: KDE
Windowing System: X11

**Comment by neildarlow** [comment]
Maintainers: Can this issue please be attended to. Without the proposed fix from @droidmonkey the Flatpak version of KeePassXC presents undesirable behaviour not observed elsewhere.

**Comment by droidmonkey** [comment]
Fixed in 2.7.4 release
